import type { Lesson } from './types'

export const directExchange: Lesson = {
  id: '02-direct',
  group: 'basics',
  title: 'Direct exchange',
  summary: 'Exact routing-key matching, and what happens when nothing matches.',
  seed: 2,
  durationMs: 10_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Direct exchange', type: 'direct', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'pay', label: 'pay', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'ship', label: 'ship', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'audit', label: 'audit', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-pay',
        label: 'Pay consumer',
        queueId: 'pay',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-ship',
        label: 'Ship consumer',
        queueId: 'ship',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-audit',
        label: 'Audit consumer',
        queueId: 'audit',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      { id: 'b1', exchangeId: 'ex', destinationId: 'pay', destinationKind: 'queue', routingKey: 'payment' },
      { id: 'b2', exchangeId: 'ex', destinationId: 'ship', destinationKind: 'queue', routingKey: 'shipping' },
      { id: 'b3', exchangeId: 'ex', destinationId: 'audit', destinationKind: 'queue', routingKey: 'payment' },
    ],
  },
  script: [
    { at: 0, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment', body: 'Payment 1' },
    { at: 1200, publisherId: 'p1', exchangeId: 'ex', routingKey: 'shipping', body: 'Shipping 1' },
    { at: 2400, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment', body: 'Payment 2' },
    { at: 3600, publisherId: 'p1', exchangeId: 'ex', routingKey: 'refund', body: 'Refund 1' },
    { at: 4800, publisherId: 'p1', exchangeId: 'ex', routingKey: 'shipping', body: 'Shipping 2' },
  ],
  narrative: [
    {
      at: 0,
      title: 'A direct exchange matches the key exactly',
      body: 'Each binding on `ex` names a routing key. A message is only routed to a binding whose key is an *exact* string match — no patterns, no partial hits.',
      highlight: ['p1', 'ex'],
    },
    {
      at: 1800,
      title: 'Two queues, one key, two copies',
      body: 'Both `pay` and `audit` are bound with the key `payment`. A message published with that key is routed to **both** — each queue gets its own independent copy.',
      highlight: ['pay', 'audit'],
    },
    {
      at: 3600,
      title: 'An unmatched key is silently discarded',
      body: 'This message carries the key `refund`, and no binding on `ex` uses that key. With no `mandatory` flag and no alternate exchange configured, the broker just drops it.',
      highlight: ['ex'],
    },
    {
      at: 6000,
      title: 'Why `mandatory` and alternate exchanges exist',
      body: 'A dropped message like the `refund` one leaves no trace at the queue. Marking a publish `mandatory`, or binding an alternate exchange to catch the leftovers, is how you avoid losing messages silently.',
      highlight: ['ex'],
    },
  ],
}
