import type { Lesson } from './types'

export const directExchange: Lesson = {
  id: '02-direct',
  group: 'basics',
  title: 'Direct exchange',
  summary: 'Routing key khớp chính xác, và điều gì xảy ra khi không có gì khớp.',
  seed: 2,
  durationMs: 10_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Direct exchange', type: 'direct', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'pay', label: 'pay', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'ship', label: 'ship', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'audit', label: 'audit', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-pay',
        label: 'Pay consumer',
        queueId: 'pay',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-ship',
        label: 'Ship consumer',
        queueId: 'ship',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-audit',
        label: 'Audit consumer',
        queueId: 'audit',
        prefetch: 1,
        autoAck: false,
        processingMs: 700,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      { id: 'b1', exchangeId: 'ex', destinationId: 'pay', destinationKind: 'queue', routingKey: 'payment' },
      { id: 'b2', exchangeId: 'ex', destinationId: 'ship', destinationKind: 'queue', routingKey: 'shipping' },
      { id: 'b3', exchangeId: 'ex', destinationId: 'audit', destinationKind: 'queue', routingKey: 'payment' },
    ],
  },
  script: [
    { at: 0, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment', body: 'Payment 1' },
    { at: 1200, publisherId: 'p1', exchangeId: 'ex', routingKey: 'shipping', body: 'Shipping 1' },
    { at: 2400, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment', body: 'Payment 2' },
    { at: 3600, publisherId: 'p1', exchangeId: 'ex', routingKey: 'refund', body: 'Refund 1' },
    { at: 4800, publisherId: 'p1', exchangeId: 'ex', routingKey: 'shipping', body: 'Shipping 2' },
  ],
  narrative: [
    {
      at: 0,
      title: 'Direct exchange khớp key một cách chính xác',
      body: 'Mỗi binding trên `ex` gán một routing key. Message chỉ được route tới binding có key khớp *chính xác* dạng string — không pattern, không khớp một phần.',
      highlight: ['p1', 'ex'],
    },
    {
      at: 1800,
      title: 'Hai queue, một key, hai bản copy',
      body: 'Cả `pay` và `audit` đều bind với key `payment`. Message publish với key đó được route tới **cả hai** — mỗi queue nhận một bản copy độc lập của riêng mình.',
      highlight: ['pay', 'audit'],
    },
    {
      at: 3600,
      title: 'Key không khớp bị âm thầm loại bỏ',
      body: 'Message này mang key `refund`, và không binding nào trên `ex` dùng key đó. Không có flag `mandatory`, cũng không có alternate exchange nào được cấu hình, nên broker đơn giản là drop nó.',
      highlight: ['ex'],
    },
    {
      at: 6000,
      title: 'Vì sao `mandatory` và alternate exchange tồn tại',
      body: 'Một message bị drop như message `refund` ở trên không để lại dấu vết nào ở queue. Đánh dấu publish là `mandatory`, hoặc bind một alternate exchange để hứng phần dư ra, chính là cách bạn tránh mất message một cách âm thầm.',
      highlight: ['ex'],
    },
  ],
}
