import type { Lesson } from './types'

export const fanoutExchange: Lesson = {
  id: '03-fanout',
  group: 'basics',
  title: 'Fanout exchange',
  summary: 'One message, broadcast to every bound queue, regardless of routing key.',
  seed: 3,
  durationMs: 9_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Fanout exchange', type: 'fanout', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'email', label: 'email', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'analytics', label: 'analytics', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'audit', label: 'audit', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-email',
        label: 'Email consumer',
        queueId: 'email',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-analytics',
        label: 'Analytics consumer',
        queueId: 'analytics',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-audit',
        label: 'Audit consumer',
        queueId: 'audit',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      {
        id: 'b1',
        exchangeId: 'ex',
        destinationId: 'email',
        destinationKind: 'queue',
        routingKey: 'ignored-a',
      },
      {
        id: 'b2',
        exchangeId: 'ex',
        destinationId: 'analytics',
        destinationKind: 'queue',
        routingKey: 'ignored-b',
      },
      {
        id: 'b3',
        exchangeId: 'ex',
        destinationId: 'audit',
        destinationKind: 'queue',
        routingKey: 'ignored-c',
      },
    ],
  },
  script: [
    { at: 0, publisherId: 'p1', exchangeId: 'ex', routingKey: 'whatever', body: 'Broadcast 1' },
    { at: 2000, publisherId: 'p1', exchangeId: 'ex', routingKey: 'whatever', body: 'Broadcast 2' },
    { at: 4000, publisherId: 'p1', exchangeId: 'ex', routingKey: 'whatever', body: 'Broadcast 3' },
  ],
  narrative: [
    {
      at: 0,
      title: 'Fanout ignores the routing key entirely',
      body: 'Every binding on `ex` carries a routing key — `ignored-a`, `ignored-b`, `ignored-c` — but a fanout exchange never looks at them. Every bound queue receives every message.',
      highlight: ['p1', 'ex'],
    },
    {
      at: 1400,
      title: 'One message becomes three copies',
      body: 'Watch the particle leave `ex` and split into three at once, one toward `email`, one toward `analytics`, one toward `audit`. Each queue gets an independent copy of the same message.',
      highlight: ['email', 'analytics', 'audit'],
    },
    {
      at: 3000,
      title: 'A slow queue never slows the others',
      body: 'Because each queue owns its own copy, a consumer that is slow to drain `audit` has no effect on how fast `email` or `analytics` are served.',
      highlight: ['email', 'analytics', 'audit'],
    },
    {
      at: 5000,
      title: 'No pattern, no exception',
      body: 'There is no routing key that would make a fanout exchange skip a bound queue. Binding to a fanout exchange is a *broadcast* subscription, full stop.',
      highlight: ['ex'],
    },
  ],
}
