import type { Lesson } from './types'

export const topicExchange: Lesson = {
  id: '04-topic',
  group: 'basics',
  title: 'Topic exchange',
  summary: 'Wildcard routing: `*` khớp một từ, `#` khớp không hoặc nhiều từ.',
  seed: 4,
  durationMs: 12_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Topic exchange', type: 'topic', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'eu-orders', label: 'eu-orders', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'all-orders', label: 'all-orders', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'created-only', label: 'created-only', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-eu-orders',
        label: 'EU orders consumer',
        queueId: 'eu-orders',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-all-orders',
        label: 'All orders consumer',
        queueId: 'all-orders',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-created-only',
        label: 'Created-only consumer',
        queueId: 'created-only',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      {
        id: 'b1',
        exchangeId: 'ex',
        destinationId: 'eu-orders',
        destinationKind: 'queue',
        routingKey: 'order.eu.*',
      },
      {
        id: 'b2',
        exchangeId: 'ex',
        destinationId: 'all-orders',
        destinationKind: 'queue',
        routingKey: 'order.#',
      },
      {
        id: 'b3',
        exchangeId: 'ex',
        destinationId: 'created-only',
        destinationKind: 'queue',
        routingKey: '*.*.created',
      },
    ],
  },
  script: [
    { at: 0, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.eu.created', body: 'Order A' },
    { at: 1800, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.us.created', body: 'Order B' },
    { at: 3600, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.eu.cancelled', body: 'Order C' },
    { at: 5400, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment.eu.created', body: 'Payment A' },
    { at: 7200, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order', body: 'Order D' },
  ],
  narrative: [
    {
      at: 0,
      title: '`*` khớp đúng một từ',
      body: 'Binding trên `eu-orders` là `order.eu.*`, nên nó khớp với key có đúng ba từ ngăn cách bởi dấu chấm: hai từ đầu cố định, từ cuối là bất kỳ. `order.eu.created` khớp; `order.eu.west.created` thì không — vì key đó thừa một từ.',
      highlight: ['p1', 'ex', 'eu-orders'],
    },
    {
      at: 3000,
      title: '`#` khớp không hoặc nhiều từ',
      body: 'Binding `order.#` trên `all-orders` khớp với `order` đứng một mình, `order.eu.created`, và bất kỳ key nào khác bắt đầu bằng `order`. Đây là wildcard lỏng lẻo nhất mà một topic exchange cung cấp.',
      highlight: ['all-orders'],
    },
    {
      at: 6000,
      title: 'Key trơn vẫn khớp `#`, nhưng không khớp `*`',
      body: 'Key `order` đứng một mình khớp `order.#` — `#` chấp nhận cả trường hợp không còn từ nào — nhưng nó **không** khớp `order.eu.*`, vốn cần đúng thêm hai từ nữa sau `order`.',
      highlight: ['all-orders', 'eu-orders'],
    },
    {
      at: 9000,
      title: 'Một message có thể rơi vào nhiều queue cùng lúc',
      body: 'Không có gì trong topic routing là độc quyền. `order.eu.created` ở trên khớp cả `eu-orders`, `all-orders`, *và* `created-only` trong cùng một lần publish — ba bản copy độc lập từ một message.',
      highlight: ['eu-orders', 'all-orders', 'created-only'],
    },
  ],
}
