import type { Lesson } from './types'

export const topicExchange: Lesson = {
  id: '04-topic',
  group: 'basics',
  title: 'Topic exchange',
  summary: 'Wildcard routing: `*` matches one word, `#` matches zero or more.',
  seed: 4,
  durationMs: 12_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Topic exchange', type: 'topic', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'eu-orders', label: 'eu-orders', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'all-orders', label: 'all-orders', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'created-only', label: 'created-only', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-eu-orders',
        label: 'EU orders consumer',
        queueId: 'eu-orders',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-all-orders',
        label: 'All orders consumer',
        queueId: 'all-orders',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-created-only',
        label: 'Created-only consumer',
        queueId: 'created-only',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      {
        id: 'b1',
        exchangeId: 'ex',
        destinationId: 'eu-orders',
        destinationKind: 'queue',
        routingKey: 'order.eu.*',
      },
      {
        id: 'b2',
        exchangeId: 'ex',
        destinationId: 'all-orders',
        destinationKind: 'queue',
        routingKey: 'order.#',
      },
      {
        id: 'b3',
        exchangeId: 'ex',
        destinationId: 'created-only',
        destinationKind: 'queue',
        routingKey: '*.*.created',
      },
    ],
  },
  script: [
    { at: 0, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.eu.created', body: 'Order A' },
    { at: 1800, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.us.created', body: 'Order B' },
    { at: 3600, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order.eu.cancelled', body: 'Order C' },
    { at: 5400, publisherId: 'p1', exchangeId: 'ex', routingKey: 'payment.eu.created', body: 'Payment A' },
    { at: 7200, publisherId: 'p1', exchangeId: 'ex', routingKey: 'order', body: 'Order D' },
  ],
  narrative: [
    {
      at: 0,
      title: '`*` matches exactly one word',
      body: 'The binding on `eu-orders` is `order.eu.*`, so it matches a key with exactly three dot-separated words: the first two literal, the last anything. `order.eu.created` fits; `order.eu.west.created` would not — that has one word too many.',
      highlight: ['p1', 'ex', 'eu-orders'],
    },
    {
      at: 3000,
      title: '`#` matches zero or more words',
      body: 'The binding `order.#` on `all-orders` matches `order` alone, `order.eu.created`, and anything else that starts with `order`. It is the loosest wildcard a topic exchange offers.',
      highlight: ['all-orders'],
    },
    {
      at: 6000,
      title: 'A bare key still matches `#`, but not `*`',
      body: 'The key `order` alone matches `order.#` — `#` is happy with zero remaining words — but it does **not** match `order.eu.*`, which needs exactly two more words after `order`.',
      highlight: ['all-orders', 'eu-orders'],
    },
    {
      at: 9000,
      title: 'A message can land in several queues at once',
      body: 'Nothing about topic routing is exclusive. `order.eu.created` above matched `eu-orders`, `all-orders`, *and* `created-only` in the same publish — three independent copies from one message.',
      highlight: ['eu-orders', 'all-orders', 'created-only'],
    },
  ],
}
