import type { Lesson } from './types'

export const headersExchange: Lesson = {
  id: '05-headers',
  group: 'basics',
  title: 'Headers exchange',
  summary: 'Routing on header values instead of the routing key, with `all` versus `any` matching.',
  seed: 5,
  durationMs: 10_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Headers exchange', type: 'headers', position: { x: 260, y: 180 } }],
    queues: [
      { id: 'pdf-reports', label: 'pdf-reports', kind: 'classic', position: { x: 480, y: 60 } },
      { id: 'anything-pdf', label: 'anything-pdf', kind: 'classic', position: { x: 480, y: 180 } },
      { id: 'csv-or-report', label: 'csv-or-report', kind: 'classic', position: { x: 480, y: 300 } },
    ],
    consumers: [
      {
        id: 'c-pdf-reports',
        label: 'PDF reports consumer',
        queueId: 'pdf-reports',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'c-anything-pdf',
        label: 'Anything PDF consumer',
        queueId: 'anything-pdf',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'c-csv-or-report',
        label: 'CSV or report consumer',
        queueId: 'csv-or-report',
        prefetch: 1,
        autoAck: false,
        processingMs: 500,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [
      {
        id: 'b1',
        exchangeId: 'ex',
        destinationId: 'pdf-reports',
        destinationKind: 'queue',
        headers: { format: 'pdf', kind: 'report' },
        xMatch: 'all',
      },
      {
        id: 'b2',
        exchangeId: 'ex',
        destinationId: 'anything-pdf',
        destinationKind: 'queue',
        headers: { format: 'pdf' },
        xMatch: 'any',
      },
      {
        id: 'b3',
        exchangeId: 'ex',
        destinationId: 'csv-or-report',
        destinationKind: 'queue',
        headers: { format: 'csv', kind: 'report' },
        xMatch: 'any',
      },
    ],
  },
  script: [
    {
      at: 0,
      publisherId: 'p1',
      exchangeId: 'ex',
      routingKey: '',
      body: 'PDF report',
      headers: { format: 'pdf', kind: 'report' },
    },
    {
      at: 2000,
      publisherId: 'p1',
      exchangeId: 'ex',
      routingKey: '',
      body: 'PDF only',
      headers: { format: 'pdf' },
    },
    {
      at: 4000,
      publisherId: 'p1',
      exchangeId: 'ex',
      routingKey: '',
      body: 'CSV file',
      headers: { format: 'csv' },
    },
    {
      at: 6000,
      publisherId: 'p1',
      exchangeId: 'ex',
      routingKey: '',
      body: 'Invoice',
      headers: { kind: 'invoice' },
    },
  ],
  narrative: [
    {
      at: 0,
      title: 'Headers exchanges ignore the routing key entirely',
      body: 'Every message here is published with an empty routing key. A headers exchange routes on the message\'s `headers` map instead, comparing it against each binding\'s header criteria.',
      highlight: ['p1', 'ex'],
    },
    {
      at: 2200,
      title: '`x-match: all` needs every header to match',
      body: '`pdf-reports` is bound with `xMatch: all` against `{format: pdf, kind: report}`. Only a message carrying **both** of those headers with those exact values is routed there.',
      highlight: ['pdf-reports'],
    },
    {
      at: 4200,
      title: '`x-match: any` needs just one',
      body: '`anything-pdf` and `csv-or-report` are both bound with `xMatch: any`. A message matching *any single* listed header — not all of them — is routed there.',
      highlight: ['anything-pdf', 'csv-or-report'],
    },
    {
      at: 6200,
      title: 'No matching header, no route',
      body: 'The last message carries only `kind: invoice`, which appears in none of the three bindings\' criteria. It matches nothing and is dropped, exactly like an unroutable direct-exchange key.',
      highlight: ['ex'],
    },
  ],
}
