import type { Lesson } from './types'

export const competingConsumers: Lesson = {
  id: '06-competing-consumers',
  group: 'basics',
  title: 'Competing consumers',
  summary: 'One queue, several consumers: work is split, not duplicated.',
  seed: 6,
  durationMs: 14_000,
  topology: {
    publishers: [{ id: 'p1', label: 'Publisher', position: { x: 40, y: 180 } }],
    exchanges: [{ id: 'ex', label: 'Direct exchange', type: 'direct', position: { x: 260, y: 180 } }],
    queues: [{ id: 'work', label: 'work', kind: 'classic', position: { x: 480, y: 180 } }],
    consumers: [
      {
        id: 'fast',
        label: 'Fast consumer',
        queueId: 'work',
        prefetch: 1,
        autoAck: false,
        processingMs: 400,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 60 },
      },
      {
        id: 'medium',
        label: 'Medium consumer',
        queueId: 'work',
        prefetch: 1,
        autoAck: false,
        processingMs: 900,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 180 },
      },
      {
        id: 'slow',
        label: 'Slow consumer',
        queueId: 'work',
        prefetch: 1,
        autoAck: false,
        processingMs: 2000,
        jitterMs: 0,
        nackRate: 0,
        requeueOnNack: true,
        position: { x: 700, y: 300 },
      },
    ],
    bindings: [{ id: 'b1', exchangeId: 'ex', destinationId: 'work', destinationKind: 'queue', routingKey: 'job' }],
  },
  script: Array.from({ length: 9 }, (_, i) => ({
    at: i * 300,
    publisherId: 'p1',
    exchangeId: 'ex',
    routingKey: 'job',
    body: `Job ${i + 1}`,
  })),
  narrative: [
    {
      at: 0,
      title: 'One queue, three competing consumers',
      body: '`fast`, `medium`, and `slow` are all bound to the same queue, `work`. This is not fanout — each message goes to exactly *one* of them. The three consumers compete for messages instead of duplicating them.',
      highlight: ['work', 'fast', 'medium', 'slow'],
    },
    {
      at: 1800,
      title: 'Delivery rotates while a consumer is free',
      body: 'With `prefetch: 1` on every consumer, the broker hands the next message to whichever eligible consumer is next in rotation — but only if that consumer is not already holding an unacked message.',
      highlight: ['work'],
    },
    {
      at: 5000,
      title: 'The slow consumer falls behind',
      body: '`slow` takes 2000ms to process a message, five times longer than `fast` at 400ms. While `slow` is still busy with one message, it is skipped, and `fast` becomes eligible again far sooner.',
      highlight: ['slow', 'fast'],
    },
    {
      at: 9000,
      title: 'Prefetch is what makes this fair, not the queue',
      body: 'The queue itself has no idea which consumer is faster. It is the prefetch ceiling of `1` that keeps a busy consumer out of rotation, letting free consumers pick up more of the total work.',
      highlight: ['work'],
    },
  ],
}
